# Generated by Django 3.2.7 on 2021-11-22 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211112_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 19, 40, 29, 134158), verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='document',
            field=models.CharField(max_length=10, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Correo Electrónico'),
        ),
    ]
