# Generated by Django 3.2.7 on 2021-11-23 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211121_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 14, 2, 14, 552276), verbose_name='Fecha de Registro'),
        ),
    ]
