# Generated by Django 3.2.7 on 2021-11-26 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 21, 17, 29, 561110), verbose_name='Fecha de Registro'),
        ),
    ]
