# Generated by Django 3.2.7 on 2021-11-26 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 12, 59, 12, 365766), verbose_name='Fecha de Registro'),
        ),
    ]
