# Generated by Django 3.2.7 on 2022-04-08 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 8, 19, 3, 0, 272291), verbose_name='Fecha de Registro'),
        ),
    ]
