# Generated by Django 3.2.7 on 2022-05-30 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 18, 1, 24, 295545), verbose_name='Fecha de Registro'),
        ),
    ]
