# Generated by Django 3.2.7 on 2022-05-10 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 22, 3, 6, 848265), verbose_name='Fecha de Registro'),
        ),
    ]
