# Generated by Django 3.2.7 on 2022-06-05 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 19, 33, 2, 62830), verbose_name='Fecha de Registro'),
        ),
    ]
