# Generated by Django 3.2.7 on 2022-06-09 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 19, 37, 15, 733574), verbose_name='Fecha de Registro'),
        ),
    ]
