# Generated by Django 3.2.7 on 2022-06-29 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_20220629_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 11, 10, 3, 184091), verbose_name='Fecha de Registro'),
        ),
    ]
