# Generated by Django 3.2.7 on 2022-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_count', models.IntegerField(default=0, verbose_name='Colaboradores')),
                ('admin_count', models.IntegerField(default=0, verbose_name='Cuentas administrador')),
                ('security_count', models.IntegerField(default=0, verbose_name='Cuentas seguridad')),
                ('camera_count', models.IntegerField(default=0, verbose_name='Cámaras')),
                ('start_date', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha Fin')),
                ('subscription_id', models.IntegerField(default=0)),
            ],
        ),
    ]
