# Generated by Django 3.2.7 on 2021-11-26 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='incidents.incidentcategory'),
            preserve_default=False,
        ),
    ]
