# Generated by Django 3.2.7 on 2022-05-10 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0004_incidentcategory_image'),
    ]

    def addDefaultCamera(apps, schema_editor):
        Camera = apps.get_model('incidents', 'Camera')
        camera = Camera(address="Test address")
        camera.save()

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
            ],
        ),
        migrations.RunPython(addDefaultCamera),
        migrations.AddField(
            model_name='incident',
            name='security_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='camera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='incidents.camera'),
            preserve_default=False,
        ),
    ]
