# Generated by Django 3.2.7 on 2022-05-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_auto_20220509_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='image',
            field=models.ImageField(blank=True, upload_to='incident_images', verbose_name='Imagen de la Incidencia'),
        ),
    ]
