# Generated by Django 3.2.7 on 2022-06-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_auto_20220530_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
    ]
