# Generated by Django 3.2.7 on 2022-06-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_camera_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='security_user',
        ),
    ]
