# Generated by Django 3.2.7 on 2022-06-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0011_remove_incident_security_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'permissions': [('use_own_camera', 'El usuario de seguridad puede utilizar sus cámaras registradas')]},
        ),
    ]
