# Generated by Django 3.2.7 on 2022-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0012_alter_camera_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='mask_type',
            field=models.CharField(choices=[('temp1', 'TEMP1'), ('temp2', 'TEMP2')], default='temp1', max_length=25),
        ),
    ]
